### ISSUE TITLE
Meta Description for all blog posts is same/default meta of website

### ISSUE THREAD

**Issue by gramythedj** [TylerMRoderick/fernfolio-11ty-template#1]
when i publish blog posts from netlify cms, then most of the time the meta description is not the one we write in the netlify cms for a specific blog post but it is always the same as the meta description   home page

**Comment by TylerMRoderick** [comment]
@gramythedj Thanks for the issue, I did not notice that. I just pushed a fix so that the page `summary` will be used in place of a meta description if one is not explicitly supplied otherwise. 

commit: 676d0ca438e5a03f796c32f05593a5640ac62136

**Comment by TylerMRoderick** [comment]
Actually, I'm going to reopen this. I think it makes more sense to add a "meta description" field for every page on the cms.

**Comment by TylerMRoderick** [comment]
Ok, there is now an optional meta description field in the cms for all new blog posts or pages.

![optional meta description](https://user-images.githubusercontent.com/5217136/128278624-a9209102-62e0-420e-96cd-27f3787b0aa1.png)
