### ISSUE TITLE
Build doesn't pass because of a `/`

### ISSUE THREAD

**Issue by abeldotam** [TylerMRoderick/fernfolio-11ty-template#13]
**Describe the bug**

The build isn't working because it can find `/src/assets/img/icon-lightbulb.svg`.
Cf. screenshot part and also the Netlify tag on the main page of the project indicate that build doesn't pass.

From what I saw, it's coming from your commit of last week: https://github.com/TylerMRoderick/fernfolio-11ty-template/commit/2e8d9287420310c3e2808d38188e9d395ccd7d10#diff-01e14f9177ecbd47a5a24c41c36e833459ea3c2d765dab88f60dd22fb5d0cbc2

You added a `/` in path (I don't understand why, but maybe you know) and build doesn't found the asset since.

It works if you remove the slash.

**To Reproduce**
Steps to reproduce the behavior from fresh install:
1. `npm i`
2. `npm start`

**Expected behavior**
This beauty.
<img width="1120" alt="image" src="https://github.com/TylerMRoderick/fernfolio-11ty-template/assets/5216201/2562513f-e667-476b-829b-fd26208755c8">

**Screenshots**
<img width="1384" alt="image" src="https://github.com/TylerMRoderick/fernfolio-11ty-template/assets/5216201/ceb043d1-a428-4fdc-90eb-e39b1f51d2bf">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 116.0.1 (64 bits)
 - Node: v20.5.0

**Additional context**
Your theme is awesome, congrats for the nice work you did. ☺️

**Comment by TylerMRoderick** [comment]
Thank you for the issue, oversight on my side to not catch this quicker.

It looks like @kpost added a fix that works great so I just merged that in. Big thank you to him!

Closing issue as resolved.
