### ISSUE TITLE
CSS not transferring when running `npm run build`

### ISSUE THREAD

**Issue by natestemen** [TylerMRoderick/fernfolio-11ty-template#15]
**Describe the bug**
When generating the build version of this website to view locally (or deploy via github actions), the website fails to connect with the CSS leaving unstyled HTML.

**To Reproduce**
1. `git clone git@github.com:TylerMRoderick/fernfolio-11ty-template.git`
2. `cd fernfolio-11ty-template`
3. `npm install`
4. `npm run build`
5. Open `_site/index.html` in the browser
6. Greeted with a webpage with (seemingly) no CSS (see screenshot below)

**Screenshots**
<img width="700" alt="Screenshot 2024-03-21 at 8 36 24 PM" src="https://github.com/TylerMRoderick/fernfolio-11ty-template/assets/12703123/9d9a6318-fb91-411d-80e2-7e1499baeb56"> 

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - Browser: Firefox
 - Version: 123.0 (64 bit)

**Additional context**
Running `npm start` works fine, and I'm able to view the website (with CSS) on `localhost`.

**Comment by TylerMRoderick** [comment]
Hey @natestemen, if your goal is to preview the build version of the website then you will need to run a web server. You can't simply open `_site/index.html` in the browser. 

One way to do this is to go into the root directory and run `npx @11ty/eleventy --serve`.

You can learn more about web servers on [this MDN article](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server). Hope that helps!

**Comment by natestemen** [comment]
Out of curiosity what are the features here that require a web server?

**Comment by TylerMRoderick** [comment]
Good question, I just took a look into `_site/index.html` to check.

If you look where the main.css file is included, you'll see `/assets/css/main.css` is a file path that doesn't resolve correctly without a web server. I believe the leading slash is what breaks things. If you replace that path with a relative path (`assets/css/main.css`), things will work without a web server.

In Eleventy, leading slashes in file paths are used to indicate that the path is relative to the root of the project. This is done to ensure that the path is always resolved correctly regardless of the current file location. If we were to run without a web server, the build step would have to only use relative paths. There is probably a way to configure things to achieve that if we wanted.
