### ISSUE TITLE
Adding/Editing Projects

### ISSUE THREAD

**Issue by alolalo** [TylerMRoderick/fernfolio-11ty-template#5]
Hello Tyler,

Thanks for this blog template, it really looks nice and I like the fact there is not a lot of Tailwind to see for once.

I am new to eleventy, but I intend to use Netlify local development mostly for setting things up correctly.

I wanted to add some more projects and I couldn't find an easy way to do that from the Netlify UI. I tried copying a MD file from projects but that didn't render any projects. I edited the index.html of a single post which does work, but copying an entire posts' folder **does not**

I finally figured out how to do this; make a copy of the MD file but make sure the title and the summary is changed because otherwise it just sees it as a duplicate entry and overwrites. 

Having this feature in the CMS is nice I think, I do lots of micro projects

**Comment by TylerMRoderick** [comment]
@alolalo Hey, thanks for the comment! 

You are right, adding a new `.md` file (with same frontmatter format as other files) in the `/projects` directory is currently the method for adding projects.

I agree that having this functionality in the CMS would be nice. I'll look into it when I get a chance, but feel free to make a PR yourself if you end up addressing it first 👍

**Comment by alolalo** [comment]
I did see Andy Bell's Eleventy course, but I'm not aware of how to create your own "section" and hook it up with Netlify. I'm a designer who loves to code and build design systems, I'm not much into software engineering despite trying to get my feet wet.

For now manual will do, but at least this way other people can read how to do it too

**Comment by TylerMRoderick** [comment]
@alolalo adding projects is now possible within the CMS. I also added various other CMS improvements to make the experience smoother overall.

Hope that helps, i'll close this issue now.

**Comment by alolalo** [comment]
Very much appreciated! I hope I can "just update" and nothing breaks...
