### ISSUE TITLE
Images for Project list on homepage

### ISSUE THREAD

**Issue by nataliehman** [TylerMRoderick/fernfolio-11ty-template#6]
Hey Tyler,

Thanks for creating this template and I'm currently using it to create my design portfolio.

I was wondering if it's possible to have an image displayed for each Project item on the homepage i.e. like blog posts with a featured image? This can be an optional feature people can choose to use or not for example.

Any suggestions is appreciated.

EDIT:

I figured out how to do this after finding this [stackoverflow question](https://stackoverflow.com/questions/71244484/using-frontmatter-as-data-in-11ty) and also [11ty's  documentation on "layouts"](https://www.11ty.dev/docs/layouts/).

If anyone have this problem this is what I did:
Let's say I have **project1.md** as the project I'm working on. For this project I want to use **project1-cover.png** as the image I want displayed on the project lists on the homepage.

In project1.md's frontmatter, I have created the field "cover" referencing the filename of that image I want to use e.g. 
title: Project 1
cover: project1-cover.png

I then add the following code into **projectlist.njk** (file is located in /_includes/components) just above the project title section of the html:
`{% if post.data.cover %}
        <div class="cover-img-container">
          <a href="{{ post.url | url }}"><img src="/static/img/{{ post.data.cover }}" alt=""></a>
        </div>
      {% endif %}`

The image should now appear on the project list on the homepage. Feel free to call "cover" to something else which make sense to you but make sure you also reference that name on areas that will be using this image with "post.data.[your field name]".

If there is a better way of doing this feel free to share but this is what I managed to get working for now.

**Comment by TylerMRoderick** [comment]
@nataliehman thanks for the comment, someone else may find it useful. And yes, I think the method you describe above is exactly right 👍.
