### ISSUE TITLE
Cannot get Passthrough file copy for custom folders/files to work

### ISSUE THREAD

**Issue by nataliehman** [TylerMRoderick/fernfolio-11ty-template#7]
**Describe the bug**
For my portfolio website, I want to also be able to upload and link to other files like PDFs. Apart from the "/static/img" folder, I want to be able to create custom folders within "/static" to keep my files organised. Currently, I can only get PDFs to load if i put it in "/static/img" folder.

I have tried going through the [11ty docs on adding the Passthrough File Copy entries](https://www.11ty.dev/docs/copy/#passthrough-file-copy) in my .eleventy.js file and tried solutions others have shared in the community but I cannot get it to work. I have tried adding the following:

- eleventyConfig.addPassthroughCopy("./static/");
- eleventyConfig.addPassthroughCopy("static");
- eleventyConfig.addPassthroughCopy({ "static": "." });
- eleventyConfig.addPassthroughCopy("static/assets"); (or any folder name after static/)
- eleventyConfig.addPassthroughCopy("**/*.pdf");

It seems like the file/folder does get copied over but both locally and live, I get 404 error. I have tested this with images not in the "/static/img" folder and it gets 404 too. Not sure if this is 11ty related or configuration of the template.

**To Reproduce**
1. Go to '.eleventy.js' file
2. Add any of the passthrough lines mentioned above
3. Compile files and test if file loads in browser
4. Either image/file doesn't load or a blank page with "Cannot GET /static/filename.pdf" if testing locally or "404. Uh oh, the resource you requested isn't here. Sorry." page if live.

**Expected behavior**
Expected PDF/file to load and be viewed/downloaded from the browser.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)

**Additional context**
Links to issues I referenced:

- [passthrough copy of .js files #1663](https://github.com/11ty/eleventy/issues/1663)
- [How do I link to a local file in a page? #1576](https://github.com/11ty/eleventy/issues/1576)
- [More detailed passthrough copy options #214](https://github.com/11ty/eleventy/issues/214)

Not sure if I've missed anything but any suggestions would be very helpful.

**Comment by TylerMRoderick** [comment]
@nataliehman just tested this out and your approach seemed to work for me.

**Steps to reproduce:**
1. Delete your `_site` directory in your project (This is the output generated by Eleventy but it may be causing issues in this case)
2. Add an `assets` folder under `static` directory.
![assets](https://user-images.githubusercontent.com/5217136/177818963-2b441986-7151-432f-970a-ae6f48b9e3c2.png)
3. Add your pdf inside `assets` folder
4. Add `eleventyConfig.addPassthroughCopy("static/assets");` to your `.eleventy.js` file
5. Run `npm start` (this will generate a new `_site` output. If you look inside, you should be able to `_site > static > assets` populated.)
6. access your file at `http://localhost:8080/static/assets/my-file.pdf`


Hope that helps 👍

**Comment by nataliehman** [comment]
@TylerMRoderick Ok I tried your solution and it worked. Thanks for the help 😃
