### ISSUE TITLE
"Error loading the CMS configuration"

### ISSUE THREAD

**Issue by futuresoup** [TylerMRoderick/fernfolio-11ty-template#9]
So excited about this! But...

**Describe the bug**
Can't log in to /admin due to a YAML syntax error

**To Reproduce**
1. Follow the installation instructions
2. When you get to the step to log in to Netlify CMS by going to /admin'
3. The error appears 

> Error loading the CMS configuration
Config Errors:

YAMLSyntaxError: All collection items must start at the same column at line 18, column 7:

    - label: "Metadata"
      ^^^^^^^^^^^^^^^^^…

Check your config.yml file.

**Expected behavior**
Access the Netlify CMS

**Screenshot**
<img width="861" alt="Screen Shot 2022-11-27 at 11 21 23 AM" src="https://user-images.githubusercontent.com/1459051/204155431-05bceb2c-4bb6-4bcb-99e3-743f81e69542.png">

**Comment by regchukwuka** [comment]
Got the same error message

**Comment by TylerMRoderick** [comment]
@futuresoup @regchukwuka thanks for creating an issue and commenting. I just updated the config file and fixed the issue. Let me know if you run into any other problems.

**Comment by regchukwuka** [comment]
Hi, Thank you for your swift response, please note that I am still
facing the same issue.

**Comment by TylerMRoderick** [comment]
@regchukwuka did you update your personal repo with the 2 newest commits (from December 7)? Maybe there was an issue with your deployment?
